// Generated by scripts/generate-db-types.mjs from src/schemas/sql — do not edit.
import type { Generated } from "kysely";

export interface AccountTable {
  id: string;
  tenant_id: string;
  external_ref: string | null;
  created_at: Generated<Date>;
}

export interface AdminAuditTable {
  id: string;
  actor: string;
  action: string;
  target: string | null;
  params: string | null;
  result: string;
  detail: string | null;
  ip: string | null;
  at: Generated<Date>;
}

export interface AgentRuleTable {
  id: string;
  tenant_id: string;
  name: string;
  condition_type: string;
  condition_threshold: string;
  action: string;
  is_active: Generated<boolean>;
  created_at: Generated<Date>;
}

export interface AiAnomalyLogTable {
  id: string;
  tenant_id: string;
  type: string;
  severity: string;
  description: string;
  context_json: Generated<string>;
  created_at: Generated<Date>;
}

export interface ApiKeyTable {
  key_hash: string;
  tenant_id: string;
  id: Generated<string>;
  label: string | null;
  scopes: Generated<string[]>;
  created_at: Generated<Date>;
  revoked_at: Date | null;
  revoked_reason: string | null;
}

export interface AuthAttemptTable {
  id: Generated<string>;
  at: Generated<Date>;
  email: string | null;
  principal_id: string | null;
  kind: string;
  outcome: string;
  ip: string | null;
  user_agent: string | null;
  detail: string | null;
}

export interface AuthSessionTable {
  id: string;
  principal_id: string;
  token_hash: string;
  csrf_token: string;
  created_at: Generated<Date>;
  last_seen_at: Generated<Date>;
  idle_expires_at: Date;
  expires_at: Date;
  revoked_at: Date | null;
  revoked_reason: string | null;
  ip: string | null;
  user_agent: string | null;
}

export interface BalanceTable {
  account: string;
  asset: string;
  amount: Generated<string>;
  version: Generated<string>;
}

export interface DepositCursorTable {
  chain: string;
  address: string;
  next_block: string;
  updated_at: Generated<Date>;
}

export interface ErrorLogTable {
  id: string;
  code: string;
  message: string;
  context: string | null;
  at: Generated<Date>;
}

export interface GatherConfigTable {
  chain: string;
  tenant: Generated<string>;
  active_strategy: string;
  updated_by: string;
  approved_by: string;
  effective_at: Generated<Date>;
}

export interface IdempotencyKeyTable {
  tenant_id: string;
  key: string;
  status: number | null;
  response: string | null;
  created_at: Generated<Date>;
}

export interface JournalEntryTable {
  id: string;
  idempotency_key: string;
  kind: string;
  occurred_at: Date;
}

export interface PayoutAllowlistTable {
  tenant: string;
  merchant: string;
  chain: string;
  address: string;
  usable_at: Date;
  added_at: Generated<Date>;
}

export interface PayoutApprovalTable {
  intent_key: string;
  approver: string;
  tenant: string;
  at: Generated<Date>;
}

export interface PayoutIntentTable {
  idempotency_key: string;
  id: Generated<string>;
  requested_by: string | null;
  tenant: string;
  merchant: string;
  chain: string;
  asset: string;
  amount_base_units: string;
  destination: string;
  from_address: string | null;
  tx_id: string | null;
  status: Generated<string>;
  last_error: string | null;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

export interface PolicyKillSwitchTable {
  scope: string;
  engaged: Generated<boolean>;
  reason: string | null;
  updated_at: Generated<Date>;
}

export interface PolicyPayoutLogTable {
  id: Generated<string>;
  tenant: string;
  merchant: string;
  asset: string;
  amount_base_units: string;
  at: Date;
}

export interface PoolAddressTable {
  id: string;
  tenant: string;
  merchant: string;
  chain: string;
  derivation_index: number;
  address: string;
  state: string;
  invoice_id: string | null;
  cooldown_until: Date | null;
  gather_strategy: Generated<string>;
  created_at: Generated<Date>;
}

export interface PoolAddressBalanceTable {
  chain: string;
  address: string;
  asset: string;
  balance_base_units: Generated<string>;
  observed_at: Generated<Date>;
  source: Generated<string>;
  last_error: string | null;
}

export interface PoolGatherLeaseTable {
  key: string;
  holder: string;
  acquired_at: Generated<Date>;
  expires_at: Date;
}

export interface PostingTable {
  id: Generated<string>;
  journal_entry_id: string;
  account: string;
  asset: string;
  amount: string;
  direction: string;
}

export interface PrincipalTable {
  id: string;
  kind: string;
  tenant_id: string | null;
  email: string;
  password_hash: string;
  role: string;
  status: Generated<string>;
  must_change_password: Generated<boolean>;
  failed_logins: Generated<number>;
  locked_until: Date | null;
  last_login_at: Date | null;
  created_at: Generated<Date>;
  disabled_at: Date | null;
}

export interface PrincipalRecoveryCodeTable {
  principal_id: string;
  code_hash: string;
  used_at: Date | null;
}

export interface PrincipalTotpTable {
  principal_id: string;
  secret: string;
  confirmed_at: Date | null;
  last_step: string | null;
  created_at: Generated<Date>;
}

export interface TenantTable {
  id: string;
  name: string;
  created_at: Generated<Date>;
}

export interface WebhookDeliveryTable {
  id: string;
  tenant_id: string;
  body: string;
  status: Generated<string>;
  attempts: Generated<number>;
  next_attempt: Generated<Date>;
  last_error: string | null;
  created_at: Generated<Date>;
}

export interface WebhookEndpointTable {
  tenant_id: string;
  url: string;
  secret: string;
}

export interface DB {
  account: AccountTable;
  admin_audit: AdminAuditTable;
  agent_rule: AgentRuleTable;
  ai_anomaly_log: AiAnomalyLogTable;
  api_key: ApiKeyTable;
  auth_attempt: AuthAttemptTable;
  auth_session: AuthSessionTable;
  balance: BalanceTable;
  deposit_cursor: DepositCursorTable;
  error_log: ErrorLogTable;
  gather_config: GatherConfigTable;
  idempotency_key: IdempotencyKeyTable;
  journal_entry: JournalEntryTable;
  payout_allowlist: PayoutAllowlistTable;
  payout_approval: PayoutApprovalTable;
  payout_intent: PayoutIntentTable;
  policy_kill_switch: PolicyKillSwitchTable;
  policy_payout_log: PolicyPayoutLogTable;
  pool_address: PoolAddressTable;
  pool_address_balance: PoolAddressBalanceTable;
  pool_gather_lease: PoolGatherLeaseTable;
  posting: PostingTable;
  principal: PrincipalTable;
  principal_recovery_code: PrincipalRecoveryCodeTable;
  principal_totp: PrincipalTotpTable;
  tenant: TenantTable;
  webhook_delivery: WebhookDeliveryTable;
  webhook_endpoint: WebhookEndpointTable;
}
