export const ADMIN_ROUTES = {
  ASSETS: "/admin/api/assets",
  AUDIT: "/admin/api/audit",
  AUTH_ATTEMPTS: "/admin/api/auth-attempts",
  DEPOSITS: "/admin/api/deposits",
  EARNINGS: "/admin/api/earnings",
  EARNINGS_SWEEP: "/admin/api/earnings/sweep",
  ERRORS: "/admin/api/errors",
  KILLSWITCH: "/admin/api/killswitch",
  KILLSWITCH_ENGAGE: "/admin/api/killswitch/engage",
  KILLSWITCH_RESET: "/admin/api/killswitch/reset",
  LEDGER_ACCOUNTS: "/admin/api/ledger/accounts",
  LEDGER_ENTRIES: "/admin/api/ledger/entries",
  OPERATORS: "/admin/api/operators",
  OPERATORS_BY_ID_DISABLE: "/admin/api/operators/:id/disable",
  OPERATORS_BY_ID_ENABLE: "/admin/api/operators/:id/enable",
  OPERATORS_BY_ID_REVOKE_SESSIONS: "/admin/api/operators/:id/revoke-sessions",
  OVERVIEW: "/admin/api/overview",
  PAYOUTS: "/admin/api/payouts",
  POOL_ADDRESSES: "/admin/api/pool-addresses",
  TENANTS: "/admin/api/tenants",
  TENANTS_BY_ID: "/admin/api/tenants/:id",
  TENANTS_BY_ID_KEYS: "/admin/api/tenants/:id/keys",
  TENANTS_BY_ID_KEYS_BY_KEY_ID_REVOKE: "/admin/api/tenants/:id/keys/:keyId/revoke",
  TENANTS_BY_ID_KEYS_ROTATE: "/admin/api/tenants/:id/keys/rotate",
  TENANTS_BY_ID_USERS: "/admin/api/tenants/:id/users",
  WALLETS_VERIFY_ONCHAIN: "/admin/api/wallets/verify-onchain",
  WEBHOOKS: "/admin/api/webhooks",
  WEBHOOKS_BY_ID: "/admin/api/webhooks/:id",
  WEBHOOKS_BY_ID_CANCEL: "/admin/api/webhooks/:id/cancel",
  WEBHOOKS_BY_ID_REPLAY: "/admin/api/webhooks/:id/replay",
} as const;

export type AdminRoutePath = (typeof ADMIN_ROUTES)[keyof typeof ADMIN_ROUTES];
