import type { Permission } from "@/auth";
import type { HttpMethod, RouteAccess } from "@/types";
import { ADMIN_ROUTES } from "./admin.routes.js";
import { AUTH_ROUTES } from "./auth.routes.js";
import { SYSTEM_ROUTES } from "./system.routes.js";
import { TENANT_ROUTES } from "./tenant.routes.js";

export const ROUTE_KEYS = [
  "GET /admin/api/assets",
  "GET /admin/api/audit",
  "GET /admin/api/auth-attempts",
  "GET /admin/api/deposits",
  "POST /admin/api/earnings/sweep",
  "GET /admin/api/earnings",
  "GET /admin/api/errors",
  "POST /admin/api/killswitch/engage",
  "POST /admin/api/killswitch/reset",
  "GET /admin/api/killswitch",
  "GET /admin/api/ledger/accounts",
  "GET /admin/api/ledger/entries",
  "POST /admin/api/operators/:id/disable",
  "POST /admin/api/operators/:id/enable",
  "POST /admin/api/operators/:id/revoke-sessions",
  "GET /admin/api/operators",
  "POST /admin/api/operators",
  "GET /admin/api/overview",
  "GET /admin/api/payouts",
  "GET /admin/api/pool-addresses",
  "POST /admin/api/tenants/:id/keys/:keyId/revoke",
  "POST /admin/api/tenants/:id/keys/rotate",
  "GET /admin/api/tenants/:id/keys",
  "POST /admin/api/tenants/:id/keys",
  "GET /admin/api/tenants/:id/users",
  "POST /admin/api/tenants/:id/users",
  "GET /admin/api/tenants/:id",
  "GET /admin/api/tenants",
  "POST /admin/api/tenants",
  "GET /admin/api/wallets/verify-onchain",
  "POST /admin/api/webhooks/:id/cancel",
  "POST /admin/api/webhooks/:id/replay",
  "GET /admin/api/webhooks/:id",
  "GET /admin/api/webhooks",
  "POST /auth/login",
  "POST /auth/logout-all",
  "POST /auth/logout",
  "POST /auth/mfa",
  "POST /auth/password",
  "GET /auth/session",
  "DELETE /auth/sessions/:id",
  "GET /auth/sessions",
  "POST /auth/totp/begin",
  "POST /auth/totp/confirm",
  "GET /health",
  "GET /metrics",
  "GET /ready",
  "DELETE /v1/accounts/:id/allowlist",
  "POST /v1/accounts/:id/allowlist",
  "GET /v1/accounts/:id/balance",
  "GET /v1/accounts/:id/deposit-addresses",
  "POST /v1/accounts/:id/deposit-addresses",
  "POST /v1/accounts/:id/withdrawals",
  "GET /v1/accounts",
  "POST /v1/accounts",
  "GET /v1/ai/anomalies",
  "POST /v1/ai/query",
  "GET /v1/ai/rules",
  "POST /v1/ai/rules",
  "GET /v1/allowlist",
  "GET /v1/balances",
  "GET /v1/chains",
  "GET /v1/deposits",
  "GET /v1/payouts",
  "GET /v1/webhook/deliveries",
  "GET /v1/webhook",
  "PUT /v1/webhook",
  "POST /v1/withdrawals/:id/approve",
] as const;

export type RouteKey = (typeof ROUTE_KEYS)[number];

export const ROUTE_ACCESS: Record<RouteKey, RouteAccess<Permission>> = {
  "GET /admin/api/assets": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/audit": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/auth-attempts": { kind: "operator", permission: "admin.operators.manage" },
  "GET /admin/api/deposits": { kind: "operator", permission: "admin.read" },
  "POST /admin/api/earnings/sweep": { kind: "operator", permission: "admin.treasury" },
  "GET /admin/api/earnings": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/errors": { kind: "operator", permission: "admin.read" },
  "POST /admin/api/killswitch/engage": { kind: "operator", permission: "admin.killswitch" },
  "POST /admin/api/killswitch/reset": { kind: "operator", permission: "admin.killswitch" },
  "GET /admin/api/killswitch": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/ledger/accounts": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/ledger/entries": { kind: "operator", permission: "admin.read" },
  "POST /admin/api/operators/:id/disable": {
    kind: "operator",
    permission: "admin.operators.manage",
  },
  "POST /admin/api/operators/:id/enable": {
    kind: "operator",
    permission: "admin.operators.manage",
  },
  "POST /admin/api/operators/:id/revoke-sessions": {
    kind: "operator",
    permission: "admin.operators.manage",
  },
  "GET /admin/api/operators": { kind: "operator", permission: "admin.operators.manage" },
  "POST /admin/api/operators": { kind: "operator", permission: "admin.operators.manage" },
  "GET /admin/api/overview": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/payouts": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/pool-addresses": { kind: "operator", permission: "admin.read" },
  "POST /admin/api/tenants/:id/keys/:keyId/revoke": {
    kind: "operator",
    permission: "admin.tenants.manage",
  },
  "POST /admin/api/tenants/:id/keys/rotate": {
    kind: "operator",
    permission: "admin.tenants.manage",
  },
  "GET /admin/api/tenants/:id/keys": { kind: "operator", permission: "admin.read" },
  "POST /admin/api/tenants/:id/keys": { kind: "operator", permission: "admin.tenants.manage" },
  "GET /admin/api/tenants/:id/users": { kind: "operator", permission: "admin.tenants.manage" },
  "POST /admin/api/tenants/:id/users": { kind: "operator", permission: "admin.tenants.manage" },
  "GET /admin/api/tenants/:id": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/tenants": { kind: "operator", permission: "admin.read" },
  "POST /admin/api/tenants": { kind: "operator", permission: "admin.tenants.manage" },
  "GET /admin/api/wallets/verify-onchain": { kind: "operator", permission: "admin.read" },
  "POST /admin/api/webhooks/:id/cancel": { kind: "operator", permission: "admin.tenants.manage" },
  "POST /admin/api/webhooks/:id/replay": { kind: "operator", permission: "admin.tenants.manage" },
  "GET /admin/api/webhooks/:id": { kind: "operator", permission: "admin.read" },
  "GET /admin/api/webhooks": { kind: "operator", permission: "admin.read" },
  "POST /auth/login": { kind: "public" },
  "POST /auth/logout-all": { kind: "session" },
  "POST /auth/logout": { kind: "public" },
  "POST /auth/mfa": { kind: "public" },
  "POST /auth/password": { kind: "session" },
  "GET /auth/session": { kind: "session" },
  "DELETE /auth/sessions/:id": { kind: "session" },
  "GET /auth/sessions": { kind: "session" },
  "POST /auth/totp/begin": { kind: "session" },
  "POST /auth/totp/confirm": { kind: "session" },
  "GET /health": { kind: "public" },
  "GET /metrics": { kind: "admin-token" },
  "GET /ready": { kind: "public" },
  "DELETE /v1/accounts/:id/allowlist": { kind: "tenant", scope: "move-funds" },
  "POST /v1/accounts/:id/allowlist": { kind: "tenant", scope: "move-funds" },
  "GET /v1/accounts/:id/balance": { kind: "tenant", scope: "read" },
  "GET /v1/accounts/:id/deposit-addresses": { kind: "tenant", scope: "read" },
  "POST /v1/accounts/:id/deposit-addresses": { kind: "tenant", scope: "move-funds" },
  "POST /v1/accounts/:id/withdrawals": { kind: "tenant", scope: "move-funds" },
  "GET /v1/accounts": { kind: "tenant", scope: "read" },
  "POST /v1/accounts": { kind: "tenant", scope: "move-funds" },
  "GET /v1/ai/anomalies": { kind: "tenant", scope: "read" },
  "POST /v1/ai/query": { kind: "tenant", scope: "read" },
  "GET /v1/ai/rules": { kind: "tenant", scope: "read" },
  "POST /v1/ai/rules": { kind: "tenant", scope: "move-funds" },
  "GET /v1/allowlist": { kind: "tenant", scope: "read" },
  "GET /v1/balances": { kind: "tenant", scope: "read" },
  "GET /v1/chains": { kind: "tenant", scope: "read" },
  "GET /v1/deposits": { kind: "tenant", scope: "read" },
  "GET /v1/payouts": { kind: "tenant", scope: "read" },
  "GET /v1/webhook/deliveries": { kind: "tenant", scope: "read" },
  "GET /v1/webhook": { kind: "tenant", scope: "read" },
  "PUT /v1/webhook": { kind: "tenant", scope: "move-funds" },
  "POST /v1/withdrawals/:id/approve": { kind: "tenant", scope: "approve" },
};

export const PUBLIC_ROUTE_PREFIXES = ["/docs"] as const;

export const routeKey = (method: string, path: string): string => `${method} ${path}`;

export function accessForRoute(
  method: string,
  pattern: string | undefined,
): RouteAccess<Permission> | undefined {
  if (!pattern) return undefined;
  return ROUTE_ACCESS[routeKey(method, pattern) as RouteKey];
}

export const isPublicPrefix = (url: string): boolean =>
  PUBLIC_ROUTE_PREFIXES.some((p) => url === p || url.startsWith(`${p}/`));

export const ROUTE_PATHS = {
  ...SYSTEM_ROUTES,
  ...AUTH_ROUTES,
  ...ADMIN_ROUTES,
  ...TENANT_ROUTES,
} as const;
