export const AUTH_ERROR_CODES = [
  "AUTH_FAILED",
  "ACCOUNT_LOCKED",
  "MFA_REQUIRED",
  "MFA_ENROLMENT_REQUIRED",
  "PRINCIPAL_EXISTS",
  "PRINCIPAL_NOT_FOUND",
  "INVALID_ROLE",
  "NOT_AUTHENTICATED",
  "FORBIDDEN",
  "CSRF_FAILED",
  "PASSWORD_CHANGE_REQUIRED",
] as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[number];
