export const CHAIN_ERROR_CODES = [
  "UNSUPPORTED_CHAIN",
  "CHAIN_MISCONFIGURED",
  "AUTHORIZATION_INVALID",
  "TRON_TX_MISMATCH",
  "POLICY_DENIED",
  "POLICY_APPROVAL_REQUIRED",
  "POLICY_TIME_LOCKED",
  "POLICY_COMPLIANCE_HOLD",
  "POLICY_SELF_APPROVAL",
  "WITHDRAWAL_NOT_FOUND",
  "FEE_TREASURY_NOT_CONFIGURED",
  "SWEEP_HALTED",
  "GAS_FLOAT_DEPLETED",
  "GAS_TREASURY_NOT_CONFIGURED",
] as const;

export type ChainErrorCode = (typeof CHAIN_ERROR_CODES)[number];
