export const POOL_ERROR_CODES = [
  "POOL_INSUFFICIENT_FUNDS",
  "POOL_ADDRESS_NOT_FOUND",
  "POOL_CONCURRENT_MODIFICATION",
  "POOL_INVALID_TRANSITION",
  "GATHER_BUSY",
  "GATHER_STRATEGY_UNKNOWN",
  "GATHER_STRATEGY_NOT_SUPPORTED",
] as const;

export type PoolErrorCode = (typeof POOL_ERROR_CODES)[number];
